<div>
    <div>
        <div class="col-xxl-6">
            @if (session()->has('success'))
                <div class="bg-green text-green p-2 rounded mb-4">
                    {{ session('success') }}
                </div>
            @endif
            <div class="card">
                <div class="card-header align-items-center d-flex">
                    <h4 class="card-name mb-0 flex-grow-1">مدیرت مدارس</h4>

                </div><!-- end card header -->

                <div class="card-body">
                    <p class="text-muted">
                        در این قسمت میتوانید استوری های وبسایت را اپلود و حذف نمایید.
                    </p>
                    <div class="live-preview">
                        <form wire:submit="submit(Object.fromEntries(new FormData($event.target)))">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label for="name" class="form-label">نام مدرسه:</label>
                                        <sup style="color: red">*</sup>

                                        <input type="text" wire:model="name" name="name" class="form-control"
                                               placeholder="مثلا:مهدی آبان" id="name">
                                        @error('name') <span class="text-danger text-sm">{{ $message }}</span> @enderror
                                    </div>
                                </div>

                                <div class="field-wrapper  mb-4" x-data="{isUploading:false,progress:0 }"
                                     x-on:livewire-upload-start="isUploading=true"
                                     x-on:livewire-upload-finish="isUploading=false"
                                     x-on:livewire-upload-error="isUploading=false"
                                     x-on:livewire-upload-progress="progress=$event.detail.progress">

                                    <label for="document" class="form-label">تصویر مدرسه :</label>
                                    <input type="file" class="form-control" id="document" wire:model="document" name="document"
                                           placeholder="">

                                    <div x-show="isUploading" class="progress mt-3 ltr">
                                        <div class="progress-bar progress-bar-striped  bg-danger progress-bar-animated"
                                             role="progressbar" x-bind:style="`width:${progress}%`" aria-valuenow="10"
                                             aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>

                                </div>
                                @error('document') <span class="text-danger text-sm">{{ $message }}</span> @enderror



                                <!--end col-->


                                <div class="col-lg-12">
                                    <div class="text-end">
                                        <button type="submit" class="btn btn-success">
                                            <span wire:loading.remove>افزودن</span>
                                            <span wire:loading="">

                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"
                                                 preserveAspectRatio="xMidYMid" width="30" height="30"
                                                 style="shape-rendering: auto; display: block; background: transparent;"
                                                 xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle
                                                        stroke-linecap="round" fill="none"
                                                        stroke-dasharray="50.26548245743669 50.26548245743669"
                                                        stroke="#ffffff"
                                                        stroke-width="8" r="32" cy="50" cx="50">
                                              <animateTransform values="0 50 50;360 50 50" keyTimes="0;1"
                                                                dur="0.6097560975609756s" repeatCount="indefinite"
                                                                type="rotate"
                                                                attributeName="transform"></animateTransform>
                                            </circle><g></g></g><!-- [ldio] generated by https://loading.io -->
                                            </svg>
                                        </span>
                                        </button>
                                    </div>
                                </div>
                                <!--end col-->
                            </div>
                            <!--end row-->
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-name mb-0">لیست مدارس </h5>
                    </div>
                    <div class="card-body">
                        <div id="alternative-pagination_wrapper" class="dataTables_wrapper dt-bootstrap5 no-footer">
                            <div class="row g-4 mb-3">
                                <div class="col-sm">
                                    <div class="d-flex justify-content-sm-end">

                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="table-responsive table-card mb-4">
                                    <table id="alternative-pagination"
                                           class="table nowrap dt-responsive align-middle table-hover table-bordered dataTable no-footer dtr-inline"
                                           style="width: 100%;" aria-describedby="alternative-pagination_info">
                                        <thead>
                                        <tr>
                                            <th tabindex="0"
                                                aria-controls="alternative-pagination" rowspan="1" colspan="1"
                                                style="width: 110.722px;" aria-sort="ascending"
                                                aria-label="شماره SR: activate to sort column descending">ردیف
                                            </th>
                                            <th tabindex="0" aria-controls="alternative-pagination"
                                                rowspan="1" colspan="1" style="width: 183.661px;"
                                                aria-label="عنوان: activate to sort column ascending">عنوان

                                            </th>

                                            <th tabindex="0" aria-controls="alternative-pagination"
                                                rowspan="1" colspan="1" style="width: 183.661px;"
                                                aria-label="تصویر بند انگشتی: activate to sort column ascending">تصویر

                                            </th>
                                            <th tabindex="0" aria-controls="alternative-pagination"
                                                rowspan="1" colspan="1" style="width: 148.661px;"
                                                aria-label="اقدام: activate to sort column ascending">اقدام
                                            </th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        @forelse($sdfrStudents as $sdfr)
                                            <tr class="odd">
                                                <td class="dtr-control " tabindex="0">
                                                    {{ $loop->iteration }}
                                                </td>
                                                <td>
                                                    <div class="d-flex align-items-center fw-medium">
                                                        <a href="javascript:void(0);"
                                                           class="currency_name">{{ $sdfr->name }}</a>
                                                    </div>
                                                </td>
                                                <td>
                                                    <button wire:click="showMedia('image', '/client/sdfr/schoolSdfr/{{$sdfr->document}}')" class="btn btn-secondary">
                                                        نمایش عکس
                                                    </button>
                                                </td>

                                                <td>
                                                    <label> نمایش :</label>
                                                    <input wire:confirm="آیا مطمئن هستید؟"
                                                           wire:change="changeStatus({{$sdfr->id}})"
                                                           {{$sdfr->status?'checked': ''}}
                                                           class="form-check-input" type="checkbox" id="form-check-default">
                                                    <br>
                                                    <button
                                                        wire:confirm="آیا از انتخاب خود برای حذف اطمینان دارید؟"

                                                        wire:click="delete({{$sdfr->id}})"
                                                        class="btn btn-sm btn-soft-danger">
                                                        <i class=" ri-delete-bin-6-line"></i>
                                                        حذف
                                                    </button>
                                                </td>
                                            </tr>

                                        @empty
                                            <tr class="noresult" style="display: block;">
                                                <div class="text-center">
                                                    <lord-icon src="https://cdn.lordicon.com/msoeawqm.json"
                                                               trigger="loop"
                                                               colors="primary:#121331,secondary:#08a88a"
                                                               style="width:75px;height:75px"></lord-icon>
                                                    <h5 class="mt-2">متاسفم! هیچ نتیجه ای یافت نشد</h5>

                                                </div>
                                            </tr>
                                        @endforelse

                                        </tbody>

                                    </table>
                                    {{$sdfrStudents->links('layouts.manager.pagination')}}

                                    <div class="noresult" style="display: none">
                                        <div class="text-center">
                                            <lord-icon src="https://cdn.lordicon.com/msoeawqm.json" trigger="loop"
                                                       colors="primary:#121331,secondary:#08a88a"
                                                       style="width:75px;height:75px"></lord-icon>
                                            <h5 class="mt-2">متاسفم! هیچ نتیجه ای یافت نشد</h5>
                                            <p class="text-muted mb-0">ما همه دپارتمان را جستجو کرده ایم، هیچ
                                                دپارتمان برای
                                                جستجوی شما پیدا نکردیم.</p>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="row">

                                <div wire:ignore.self class="modal fade" id="selfieModal" tabindex="-1" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered">
                                        <div class="modal-content">
                                            <div class="modal-header bg-light p-3">
                                                <h5 class="modal-name">مشاهده مدیا</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="بستن"></button>
                                            </div>
                                            <div class="modal-body text-center">
                                                @if($mediaType === 'image')
                                                    <img src="{{ $selectedMedia }}" alt="Image" class="img-fluid rounded shadow" style="max-height: 500px;">
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--end col-->
        </div>
    </div>
    @push('script')
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="/admin/assets/libs/prismjs/prism.js"></script>
        <script src="/admin/assets/libs/list.js/list.min.js"></script>
        <script src="/admin/assets/libs/list.pagination.js/list.pagination.min.js"></script>
        <script src="/admin/assets/js/pages/listjs.init.js"></script>

        <script>
            document.addEventListener('DOMContentLoaded', function () {
                Livewire.on('open-selfie-modal', () => {
                    new bootstrap.Modal(document.getElementById('selfieModal')).show();
                });

                Livewire.on('open-national-modal', () => {
                    new bootstrap.Modal(document.getElementById('nationalCardModal')).show();
                });
            });
        </script>

    @endpush
</div>
